### PR TITLE
Fixes the xlocale.h removal from glibc 2.26

### PR DESCRIPTION
**Pull request by bitstopper**

### CODE REVIEW

**Comment by pulcheri** [comment]
@RobDangerous  please merge.

**Review by pulcheri — APPROVED** [review]

**Comment by RobDangerous** [comment]
Want to look into recent hxcpp changes first.

**Comment by RobDangerous** [comment]
Just merged in the changes, does this work now or do we still need the pull request?

**Comment by RobDangerous** [comment]
Hm, please reopen if there's still an issue to solve here.

**Pull request closed without merging**
