### PR TITLE
Fixed deadlock on process termination for Linux target

### PR DESCRIPTION
**Pull request by defufna**
Explanation of the problem solved can be found here

https://gist.github.com/defufna/be79a3e1690d72246b903147cc0f37dd

### CODE REVIEW

**Comment by RobDangerous** [comment]
Haha, very nice.

**Comment by RblSb** [comment]
After this patch crashes at the start of app on android inside `kinc_event_signal` called from there https://github.com/Kode/khacpp/blob/8c5e510ff5e4a54550cd356e8a2c20e5abc0e2a5/include/hx/Thread.h#L335
Called from there https://github.com/Kode/khacpp/blob/bc626b8978de6ed3d0fdcef74f46e3ea45fc5309/src/hx/gc/Immix.cpp#L4592

**Comment by romamik** [comment]
We also get this crash. This is due to unaligned memory access. 
The change in `Immix.cpp` from
```cpp
ThreadPoolSignal sThreadWake[MAX_MARK_THREADS];
``` 
to 
```cpp
uint8_t          sThreadWake[MAX_MARK_THREADS*sizeof(ThreadPoolSignal)];
```
is the reason for this. In first case compiler aligns structures appropriately, in the second it does not. 

Not sure how this helps with the original deadlock problem on linux. May be it is possible to revert changes in `Immix.cpp`, while leaving changes in `Thread.h`? If not, then some conditional compilation needed...

**Comment by defufna** [comment]
That was a hack to prevent HxSemaphore's destructor from being called on application shutdown, while avoiding allocation. I think the best fix would be to change it to:

`ThreadPoolSignal* sThreadWake[MAX_MARK_THREADS];`

That way we can still avoid destructor being called on shutdown while avoiding alignment problem.

**Comment by RobDangerous** [comment]
Already fixed it :-P

**Pull request merged**
